version: '3'
services:
  fastapi:
    build:
      context: ./fastapi
    ports:
      - "80:80"
    volumes:
      - ./fastapi:/app
    depends_on:
      - downloader

  downloader:
    build:
      context: ./data_downloader
    volumes:
      - ./data_downloader:/app/data_downloader
